### ISSUE TITLE
Please update to 3.0.5

### ISSUE THREAD

**Issue by Kirtai** [flathub/net.fsuae.FS-UAE#12]
As seen [here](https://fs-uae.net/download#source) the latest release if 3.0.5.

I have no idea why this is not announced anywhere, even on their sites news...

**Comment by hfiguiere** [comment]
The only change:

> * Packaging change to satisfy Apple's changed notarization process (sigh).

So it's not even relevant to flatpak users.

**Comment by Kirtai** [comment]
Ugh, where did you find that? I wish he'd put the release notes somewhere easier to find...

Thanks

**Comment by hfiguiere** [comment]
There is a ChangeLog in the tarball, and I did a diff with the previous one, also.

I agree, it's a mess. Not even tags in git.
